# Development - Environment configurations,

server:
  port: 1234

spring:
  application:
    name: Product-Service
  datasource:
    url: jdbc:h2:mem:productdb
    driver-class-name: org.h2.Driver
    username: root
    password: boss
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      
      
logging:
  level:
    org.springframework.web: ERROR
    com.product.controller: DEBUG
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} -%msg%n' 
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread]%-5level%logger{36} -%msg%n'
  logging.file: C:/Users/Public/Desktop/log files/api.log