# development Environment configurations,

server:
  port: 8080
  
spring:
  application:
    name: Product-Service
    
  data:
    mongodb:
      database: productdb
      host: localhost
      port: 27017
      repositories:
        enabled: true
        type: auto